name: Test and update CRC files review process

on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - "main"
            
jobs:
    build-and-test-script:
        name: build and test script
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: true
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
          - name: Checkout main branch
            uses: actions/checkout@v3
          - name: Setup Python3
            uses: actions/setup-python@v3
            with:
              python-version: 3.11
          - name: Install Dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
          - name: Run test
            run: |
              python script_tester.py

    build-docker-image:
        name: build docker image
        needs: build-and-test-script
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: true
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
          - name: Checkout main branch
            uses: actions/checkout@v3
          - name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_TOKEN }}
          - name: Build Docker image
            uses: docker/setup-buildx-action@v4
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/crc_files_review_process
              
