name: Test and update CRC files review process

on:
    push:
        branches:
            - "main"
    pull_request:
        branches:
            - "main"
            
jobs:
    build-and-test-script:
        name: build and test script
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: true
          matrix:
            os: [ubuntu-latest]
        steps:
          - name: Checkout main branch
            uses: actions/checkout@v3
          - name: Setup Python3
            uses: actions/setup-python@v3
            with:
              python-version: 3.11
          - name: Install Dependencies
            run: |
              pip3 install -r requirements.txt
          - name: Run test
            run: |
              python script_tester.py

    docker-build:
      needs: build-and-test-script
      name: Deploy to docker-build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout main branch
          uses: actions/checkout@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/crc_files_review_process

  
